name: deploy
on: [push]
jobs:
  push-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install packages
        run: npm install

      - name: build app
        run: npm run build

      - name: sync build output to s3
        run: aws s3 sync ./dist s3://${{secrets.BUCKETNAME}}
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
